// <auto-generated />
using System;
using Casalia.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Casalia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CasaliaDbContext))]
    [Migration("20261001204544_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Casalia.Domain.Entities.Abertura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Alto")
                        .HasColumnType("double precision");

                    b.Property<double>("Ancho")
                        .HasColumnType("double precision");

                    b.Property<long?>("ModeloId")
                        .HasColumnType("bigint");

                    b.Property<long>("SuperficieId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("U")
                        .HasColumnType("double precision");

                    b.Property<double>("V")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.HasIndex("SuperficieId");

                    b.ToTable("Aberturas");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Acabado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlTextura")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Acabados");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Ambiente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("double precision");

                    b.Property<long>("DisenoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DisenoId");

                    b.ToTable("Ambientes");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Diseno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AutorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Presupuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Disenos");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.ElementoEnDiseno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DisenoId")
                        .HasColumnType("bigint");

                    b.Property<double>("Escala")
                        .HasColumnType("double precision");

                    b.Property<long>("ModeloId")
                        .HasColumnType("bigint");

                    b.Property<double>("PosicionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PosicionY")
                        .HasColumnType("double precision");

                    b.Property<double>("PosicionZ")
                        .HasColumnType("double precision");

                    b.Property<double>("Rotacion")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DisenoId");

                    b.HasIndex("ModeloId");

                    b.ToTable("ElementosEnDiseno");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Modelo3D", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AltoReal")
                        .HasColumnType("double precision");

                    b.Property<double>("AnchoReal")
                        .HasColumnType("double precision");

                    b.Property<long?>("CreadorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProfundidadReal")
                        .HasColumnType("double precision");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.ToTable("Modelos3D");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Superficie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcabadoId")
                        .HasColumnType("bigint");

                    b.Property<long>("AmbienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("AcabadoId");

                    b.HasIndex("AmbienteId");

                    b.ToTable("Superficies");

                    b.HasDiscriminator<string>("Tipo").HasValue("Superficie");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("ProveedorAuth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Pared", b =>
                {
                    b.HasBaseType("Casalia.Domain.Entities.Superficie");

                    b.Property<double>("PuntoFinX")
                        .HasColumnType("double precision");

                    b.Property<double>("PuntoFinZ")
                        .HasColumnType("double precision");

                    b.Property<double>("PuntoInicioX")
                        .HasColumnType("double precision");

                    b.Property<double>("PuntoInicioZ")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Pared");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Piso", b =>
                {
                    b.HasBaseType("Casalia.Domain.Entities.Superficie");

                    b.HasDiscriminator().HasValue("Piso");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Techo", b =>
                {
                    b.HasBaseType("Casalia.Domain.Entities.Superficie");

                    b.HasDiscriminator().HasValue("Techo");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Abertura", b =>
                {
                    b.HasOne("Casalia.Domain.Entities.Modelo3D", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Casalia.Domain.Entities.Superficie", "Superficie")
                        .WithMany("Aberturas")
                        .HasForeignKey("SuperficieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");

                    b.Navigation("Superficie");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Ambiente", b =>
                {
                    b.HasOne("Casalia.Domain.Entities.Diseno", "Diseno")
                        .WithMany("Ambientes")
                        .HasForeignKey("DisenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diseno");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Diseno", b =>
                {
                    b.HasOne("Casalia.Domain.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.ElementoEnDiseno", b =>
                {
                    b.HasOne("Casalia.Domain.Entities.Diseno", "Diseno")
                        .WithMany("Elementos")
                        .HasForeignKey("DisenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casalia.Domain.Entities.Modelo3D", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diseno");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Modelo3D", b =>
                {
                    b.HasOne("Casalia.Domain.Entities.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Superficie", b =>
                {
                    b.HasOne("Casalia.Domain.Entities.Acabado", "Acabado")
                        .WithMany()
                        .HasForeignKey("AcabadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Casalia.Domain.Entities.Ambiente", "Ambiente")
                        .WithMany("Superficies")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acabado");

                    b.Navigation("Ambiente");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Ambiente", b =>
                {
                    b.Navigation("Superficies");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Diseno", b =>
                {
                    b.Navigation("Ambientes");

                    b.Navigation("Elementos");
                });

            modelBuilder.Entity("Casalia.Domain.Entities.Superficie", b =>
                {
                    b.Navigation("Aberturas");
                });
#pragma warning restore 612, 618
        }
    }
}
